wled_instances:
- host: 192.168.1.100
  start: 0
  end: 629
  display:
    chase_speed: 198
    chase_intensity: 117
    min_team_pct: 0.07
    contested_zone_pixels: 5
    dark_buffer_pixels: 3
  post_game:
    action: preset
    preset_id: 1
- host: wledhouse.witekdivers.com
  start: 0
  end: 629
poll_interval: 30
display:
  divider_color:
  - 200
  - 80
  - 0
  min_team_pct: 0.05
  contested_zone_pixels: 6
  dark_buffer_pixels: 4
  transition_ms: 500
  chase_speed: 185
  chase_intensity: 190
