wled_instances:
- host: 192.168.20.108
  start: 0
  end: 629
poll_interval: 30
display:
  divider_color:
  - 200
  - 80
  - 0
  min_team_pct: 0.05
  contested_zone_pixels: 6
  dark_buffer_pixels: 4
  transition_ms: 500
  chase_speed: 185
  chase_intensity: 190
simulator:
  league: nfl
  home: GB
  away: CHI
  win_pct: 50
